In [3]:
import numpy as np
from sympy import *

### 1. Вычислите значения выражений:
![pic1.png](https://i.ibb.co/SK2Wmrh/gjhm.jpg)

In [137]:
A = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7]) #Задание 1
B = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3])
np.dot(A, B) * 3 * 2

1632

In [140]:
A = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2]) #Задание 2
B = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8])
np.dot(A, B) * 6 * 5

4950

In [142]:
A = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7]) #Задание 3
B = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3])
np.dot(A, B)

272

In [141]:
A = np.array([9, 6, 7, 7, 0, 1, 6, 8, 1, 2]) #Задание 4
B = np.array([0, 2, 2, 6, 7, 8, 8, 3, 1, 8])
np.dot(A, B)

165

### 2.  Для следующих заданий сделайте в Python функцию, реализующую транспонирование матрицы произвольной размерности, пользуясь данным в модуле определением. Функция должна принимать и возвращать либо numpy.array, либо двумерный список (list). С помощью написанной вами функции выполните следующие задания:


![pic2.png](https://i.ibb.co/gDGs1gx/12314.png)

In [143]:
def tranp(A): # функция транспонирования
    A_tr = np.empty((A.shape[1], A.shape[0]))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            A_tr[j,i] = A[i,j]
    return A_tr

In [45]:
A = np.array([[2, 1, 7, 4],\
            [5, 6, 7, 3],\
            [9, 8, 2, 12],\
            [11, 14, 15, 15]])

In [48]:
A_tr = tranp(A).astype(int)
A_tr

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [50]:
A.T

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [52]:
np.array_equal(A.T, A_tr)

True

In [53]:
B = np.array([[3, 7, 8, 3, 6], \
              [2, 5, 9, 4, 13]])

In [55]:
B_tr = tranp(B).astype(int)
B_tr

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

In [57]:
B.T

array([[ 3,  2],
       [ 7,  5],
       [ 8,  9],
       [ 3,  4],
       [ 6, 13]])

In [59]:
np.array_equal(B.T, B_tr)

True

### 3. Завершите начатый в последнем уроке градиентный спуск. Вы можете решать эту задачу с помощью SymPy или вручную. Двигайтесь из точки в точку в направлении антиградиента, размер шага оставьте равным 0.01. Обратите внимание, что в каждой новой точке антиградиент будет разным. Добейтесь величины MSE меньше 6,36. Сколько шагов градиентного спуска вам потребовалось для этого?

In [86]:
a2, a1, x, y = symbols('a2, a1, x , y')

In [91]:
MSE = 1/4 * ((1*a1 + 2*a2 - 5)**2 + \
             (5*a1 + 3*a2 - 6)**2 + \
             (2*a1 + 4*a2 - 10)**2 + \
             (3*a1 + 7*a2 - 8)**2)

In [144]:
x_coord = 0
y_coord = 0
cnt = 0
while MSE.subs({a1: x_coord, a2: y_coord}) > 6.35:
    print('MSE=', MSE.subs({a1: x_coord, a2: y_coord}))
    x_coord, y_coord = x_coord + (-0.01*grad_MSE[0].subs({a1: x_coord, a2: y_coord})), \
    y_coord + (-0.01*grad_MSE[1].subs({a1: x_coord, a2: y_coord}))
    cnt += 1
print('Количество итераций равно ', cnt)

MSE= 56.2500000000000
MSE= 16.8572437500000
MSE= 8.59365482859375
MSE= 6.85191449679269
MSE= 6.47725148826285
MSE= 6.38978037646670
MSE= 6.36322055427526
MSE= 6.35010849011797
Количество итераций равно  8
