<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[5.92513626e-01 2.49831308e-02 3.91526339e-01 ... 9.02433469e-01
  3.84500701e-03 9.68172008e-01]
 [3.32878140e-01 7.01504017e-01 3.96451846e-01 ... 3.78727428e-01
  2.08006178e-01 4.91717517e-01]
 [9.70486362e-01 6.25228127e-02 8.78577845e-01 ... 2.95113216e-01
  5.38974802e-01 2.28891119e-01]
 ...
 [5.15736538e-01 9.39355516e-02 2.31982761e-01 ... 7.64188340e-04
  1.79890667e-01 1.66115400e-01]
 [2.08618160e-01 8.24980363e-01 3.18079500e-02 ... 8.85621744e-01
  4.27190147e-01 4.67783442e-01]
 [5.75142414e-01 6.06977211e-01 5.59254144e-01 ... 5.17798165e-01
  6.19662923e-01 8.53312965e-01]]
[[0.4281095  0.62106484 0.57367534 ... 0.44151518 0.26970044 0.78222193]
 [0.6269033  0.36595705 0.80695186 ... 0.7390893  0.38285206 0.54455896]
 [0.15492606 0.75985991 0.75993882 ... 0.27006416 0.79536803 0.05874675]
 ...
 [0.57051515 0.36864891 0.42915748 ... 0.45752313 0.9291149  0.77609505]
 [0.828275   0.42831333 0.10604967 ... 0.50995439 0.88603015 0.76491553]
 [0.55516823 0.97670987 0.5485

In [3]:
def mult(a, b):
    res = np.zeros((len(a), len(b[0])))
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range (len(b)):
                res[i][j] +=  a[i][k] * b[k][j]
    return res.tolist()



In [4]:
def np_mult(a, b):
    return(a.dot(b))
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.38 s, sys: 4.27 ms, total: 1.39 s
Wall time: 1.4 s


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 2.74 ms, sys: 4.12 ms, total: 6.86 ms
Wall time: 10.1 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.518429826319334e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.62392709 0.14714863 0.55252793] [0.61798438 0.63096929 0.24220069]


In [9]:
def scalar_product(a,b):
    return sum([(a[i] * b[i]) for i in range(len(a))])


In [10]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [11]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 51 µs, sys: 8 µs, total: 59 µs
Wall time: 33.9 µs
CPU times: user 39 µs, sys: 6 µs, total: 45 µs
Wall time: 50.3 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [12]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    s = 0
    for i in a.diagonal():
        print(i)
        if i % 2 == 0:
            s += i
    return s


In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 7, 3, 7, 6],
       [4, 8, 3, 2, 1],
       [8, 4, 4, 1, 7],
       [5, 8, 4, 8, 2],
       [9, 5, 6, 4, 7]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

4
8
4
8
7
CPU times: user 3.01 ms, sys: 0 ns, total: 3.01 ms
Wall time: 3.33 ms


24

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


​

​ 

In [15]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    return np.cumsum(A, axis = -1)

In [16]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

CPU times: user 42 µs, sys: 6 µs, total: 48 µs
Wall time: 53.9 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [18]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    X_tr = np.copy(X)
    X_tr[:, 0::2] **= 3
    X_tr[:, 1::2] = a
    X_tr = X_tr[:, ::-1]
    return np.hstack((X,X_tr))

In [25]:
X = np.array([[i for i in range(1, 10, 2)], [i for i in range(1, 10, 2)]])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)
S2

CPU times: user 147 µs, sys: 21 µs, total: 168 µs
Wall time: 137 µs


array([[  1,   3,   5,   7,   9, 729,   5, 125,   5,   1],
       [  1,   3,   5,   7,   9, 729,   5, 125,   5,   1]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [62]:
# функция, решающая задачу с помощью NumPy
import itertools
def np_encode(a):
    return np.array([x for x, y in itertools.groupby(a)]), np.array([len(list(y)) for x, y in itertools.groupby(a)])


In [65]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)
x, num

CPU times: user 56 µs, sys: 6 µs, total: 62 µs
Wall time: 66.5 µs


(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))